### PR TITLE
Manage filters on aggregates

### PR DESCRIPTION
**Pull request by boblefrag**
This is a WIP, I need to Not be merged yet

### CODE REVIEW

**Comment by rodo** [comment]
Ok so, I won't merged until a comment from you.

**Comment by boblefrag** [comment]
Or get a look and go ahead if you like to.

**Comment by boblefrag** [comment]
Nahhhh it's uglier than ugly :case specific, prints left behind... But get a look at the taxidermy of the WhereNode fort instructional purpose.

**Comment by boblefrag** [comment]
@rodo ready to review if you think it's good enought to be merged go ahead

**Pull request merged**
