### PR TITLE
Travis should build more that the default test suite

### PR DESCRIPTION
**Pull request by brunobord**
refs #57

- [x] refactor tox.ini
- [x] add the django16 suite to the travis.yml

### CODE REVIEW

**Comment by rodo** [comment]
Could we support right now Django 1.7 and 1.8 ? It would be perfect if you can add them to tox or Travis check, thanks

**Comment by brunobord** [comment]
@rodo, yup, it's perfectly testable. Will amend the PR

**Comment by brunobord** [comment]
@rodo quick update: I've tested locally and it's not automagic: builds using django 1.7 or 1.8 fail. I think we'll need to work a bit more on this. I'll open a separate issue.

**Comment by rodo** [comment]
Ok thanks for the test, so I merge this version and look forward for other version

**Pull request merged**
